# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"@\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x12\x10\n\x08leaseRem\x18\x03 \x01(\x02\"\xaf\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\x12\x15\n\rleaseDuration\x18\x07 \x01(\x02\"@\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"%\n\x12ServeClientRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"G\n\x10ServeClientReply\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xce\x01\n\x0bRaftService\x12\x33\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x0f.raft.VoteReply\"\x00\x12G\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\"\x00\x12\x41\n\x0bServeClient\x12\x18.raft.ServeClientRequest\x1a\x16.raft.ServeClientReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=111
  _globals['_VOTEREPLY']._serialized_start=113
  _globals['_VOTEREPLY']._serialized_end=177
  _globals['_APPENDENTRIESREQUEST']._serialized_start=180
  _globals['_APPENDENTRIESREQUEST']._serialized_end=355
  _globals['_APPENDENTRIESREPLY']._serialized_start=357
  _globals['_APPENDENTRIESREPLY']._serialized_end=421
  _globals['_LOGENTRY']._serialized_start=423
  _globals['_LOGENTRY']._serialized_end=464
  _globals['_SERVECLIENTREQUEST']._serialized_start=466
  _globals['_SERVECLIENTREQUEST']._serialized_end=503
  _globals['_SERVECLIENTREPLY']._serialized_start=505
  _globals['_SERVECLIENTREPLY']._serialized_end=576
  _globals['_RAFTSERVICE']._serialized_start=579
  _globals['_RAFTSERVICE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
